# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bhf}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Anton Pawlik"]
  s.date = %q{2011-01-29}
  s.description = %q{Gets you there in time}
  s.email = %q{anton.pawlik@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "app/controllers/bhf/bhf_controller.rb",
    "app/controllers/bhf/entries_controller.rb",
    "app/controllers/bhf/pages_controller.rb",
    "app/helpers/bhf/bhf_helper.rb",
    "app/helpers/bhf/entries_helper.rb",
    "app/models/bhf/base.rb",
    "app/views/bhf/bhf/index.haml",
    "app/views/bhf/entries/_form.haml",
    "app/views/bhf/entries/_validation_errors.haml",
    "app/views/bhf/entries/edit.haml",
    "app/views/bhf/entries/form/belongs_to/_radio.haml",
    "app/views/bhf/entries/form/belongs_to/_select.haml",
    "app/views/bhf/entries/form/belongs_to/_static.haml",
    "app/views/bhf/entries/form/column/_boolean.haml",
    "app/views/bhf/entries/form/column/_date.haml",
    "app/views/bhf/entries/form/column/_number.haml",
    "app/views/bhf/entries/form/column/_static.haml",
    "app/views/bhf/entries/form/column/_string.haml",
    "app/views/bhf/entries/form/column/_text.haml",
    "app/views/bhf/entries/form/has_and_belongs_to_many/_check_box.haml",
    "app/views/bhf/entries/form/has_and_belongs_to_many/_static.haml",
    "app/views/bhf/entries/form/has_many/_check_box.haml",
    "app/views/bhf/entries/form/has_many/_static.haml",
    "app/views/bhf/entries/form/has_one/_static.haml",
    "app/views/bhf/entries/new.haml",
    "app/views/bhf/entries/show.haml",
    "app/views/bhf/helper/_node.haml",
    "app/views/bhf/pages/macro/_belongs_to.haml",
    "app/views/bhf/pages/macro/_column.haml",
    "app/views/bhf/pages/macro/_has_and_belongs_to_many.haml",
    "app/views/bhf/pages/macro/_has_many.haml",
    "app/views/bhf/pages/macro/_has_one.haml",
    "app/views/bhf/pages/show.haml",
    "app/views/layouts/bhf.haml",
    "config/locales/en.yml",
    "config/routes.rb",
    "lib/bhf.rb",
    "lib/bhf/active_record.rb",
    "lib/bhf/form.rb",
    "lib/bhf/lists.rb",
    "lib/bhf/settings.rb",
    "lib/engine.rb",
    "lib/rails/generators/bhf/templates/initializer.rb",
    "public/javascripts/bhf.js",
    "public/stylesheets/bhf.css"
  ]
  s.homepage = %q{http://github.com/antpaw/bahnhof}
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{nowarning}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Agnostic rails backend}
  s.test_files = [
    "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<haml>, [">= 0"])
    else
      s.add_dependency(%q<haml>, [">= 0"])
    end
  else
    s.add_dependency(%q<haml>, [">= 0"])
  end
end

